//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Content
    {
        public string header { get; set; }
        public string footer { get; set; }
        public string content { get; set; }
        public int pageId { get; set; }
        public int version { get; set; }
    }
}
