//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Latest_Version
    {
        public Page_Latest_Version()
        {

        }

        public Page_Latest_Version(int pageNo, int version)
        {
            pageId = pageNo;
            latestVersion = version;
        }
        public int id { get; set; }
        public int pageId { get; set; }
        public int latestVersion { get; set; }
    
        public virtual Page_Details Page_Details { get; set; }
    }
}
