//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Content
    {
        public Page_Content()
        { }
        public Page_Content(string headerText, string bodyText, int pageNo, int versionNo)
        {
            header = headerText;
            content = bodyText;
            pageId = pageNo;
            version = versionNo;
        }

        public string header { get; set; }
        public string footer { get; set; }
        public string content { get; set; }
        public int pageId { get; set; }
        public int version { get; set; }
        public int id { get; set; }
    
        public virtual Page_Details Page_Details { get; set; }
    }
}
