//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page_Details()
        {
            this.Page_Content = new HashSet<Page_Content>();
            this.Page_Latest_Version = new HashSet<Page_Latest_Version>();
        }
        public Page_Details(bool isOwnerd, int pageNo, List<Page_Content> pageList, string username, List<Page_Latest_Version> versions)
        {
            pageId = pageNo;
            owner = username;
            Page_Content = pageList;
            Page_Latest_Version = versions;
        }
        public int pageId { get; set; }
        public string owner { get; set; }
        public Nullable<bool> isOwnedPage { get; set; }
        public Nullable<int> id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page_Content> Page_Content { get; set; }
        public virtual User_Details User_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Page_Latest_Version> Page_Latest_Version { get; set; }
    }
}
